91 칩 진척도 컴포넌트 구현
Team-Taskify/Taskify-Web pull request #105
Opened 2024-02-02 18:52 UTC by muyahho

많은도움을 주신 J미소천사님과 와이나경님께 감사인사를 드립니다.^^
## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
import ProgressChip from "@/components/commons/ui-progress-chip/ProgressChip";
import classNames from 'classnames/bind';
import styles from './index.module.scss';

const cx = classNames.bind(styles);

export default function Home() {

  return (
    <div>
      <div className={cx('container')}>
      <ProgressChip text="On Progress" size='onProgress'/>
      <ProgressChip text="Done" size='done'/>
      <ProgressChip text="To Do" size='toDo'/>
      </div>
    </div>
  );
}

.container {
    margin-left: 5rem;
    margin-top: 5rem;
  display: flex;
  gap: 5rem;
}

## 관련 티켓 및 문서

- Related Issue #91 
- Closes #91 

## 스크린샷, 녹화
![스크린샷 2024-02-03 031742](https://github.com/Team-Taskify/Taskify-Web/assets/88885994/6de159c9-f687-478d-a0c0-3b58036984ed)

_변경사항을 테스트하는 방법, 테스트에 사용된 기기 및 브라우저, UI 변경에 대한 관련 이미지 등에 대한 지침을 이곳에 기재해 주세요._

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

## [선택사항] 이 PR을 가장 잘 설명하는 GIF는 무엇인가요?
![image](https://github.com/Team-Taskify/Taskify-Web/assets/88885994/ca5fe4f9-ad61-4b71-886c-102c9bac6014)

2024-02-03 03:53 UTC, jeongseongwon94 approved these changes
고생하셨습니다.

2024-02-03 05:11 UTC, nakyoung98 requested changes

2024-02-03 05:11 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.module.scss
> +  &.done {
이거 어떤 데이터가 들어올지 몰라서 이렇게 제한하는건 안됨다! 같이해보죠

2024-02-03 05:11 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.tsx
> +      <span className={cx('text')}>{text}</span>
이건 넘 잘하셨어요

2024-02-03 05:22 UTC, muyahho commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.module.scss
> +  &.done {
넵 감사합니다!

2024-02-03 05:22 UTC, muyahho commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.tsx
> +      <span className={cx('text')}>{text}</span>
ㅎㅎ 덕분입니다 감사합니다

2024-02-03 05:32 UTC, SeanKim-416 approved these changes

2024-02-03 05:32 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.module.scss
> +  }
나경님이 지적하신대로 데이터가 어떻게 들어갈지 모릅니다! 클래스명은 추후에 바꿔야 될 수도 있겠군요

2024-02-04 04:20 UTC, dahee0401 approved these changes

2024-02-04 04:20 UTC, muyahho commented on taskify-web/src/components/commons/ui-progress-chip/ProgressChip.module.scss
> +  }
그렇네요! 네 클래스명은 변경해야 할것같습니다

2024-02-06 04:06 UTC, merged