Feat117 할일 생성 모달 구현
Team-Taskify/Taskify-Web pull request #127
Opened 2024-02-06 08:17 UTC by jeongseongwon94

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
git stash를안하고 develop 브랜치로 갔다오다가 자동저장이되어버려서 commit내역은 자동저장된 부분 이후부터 작성했습니다 ㅠ

### CreateCardModal 컴포넌트
props 설명
- isOpen : 모달창의 켜고 닫습니다.
- onClick : 모달창을 닫는 취소버튼에 이벤트핸들러를 전달합니다.
- columnIdNumber : 상위 컬럼 컴포넌트에서 columnId값을 받아옵니다.

### 수정 / 추가사항
Calendar.module.scss - 날짜 입력하는 인풋창의 크기를 조절하였습니다.

chipSubject.tsx/module.scss - 태그칩의 색상을 랜덤하게 받아오도록 구현하였습니다.

ProfileLabel.tsx - ProfileLabel, UserChip 컴포넌트 모두 크기조절하는 props를 받고있어서 동일한 컴포넌트명을 내려받도록 location 값을 {position}으로 수정하였습니다.

TagInput - 태그칩을 인풋창에 입력하여  표시하는 컴포넌트를 구현하였습니다.

UserStateDropdown -  상위 컴포넌트에서 state를 관리하도록 수정하였습니다.

global.scss - datepicker(클릭시 표시되는 달력) 사이즈 변경을 하려면 global파일에서만 접근이 가능하더라고요 ㅎㅎ; 
달력 크기와 달력 폰트사이즈 수정하였습니다. 

## 관련 티켓 및 문서

- Related Issue #117 
- Closes #117 

## 스크린샷, 녹화

- 모달 창 켜고 닫기 
![모달 취소](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/75e83456-9d4d-48b0-9bc3-139f7e9f4d91)

- 카드 생성 API 요청
![카드생성-min](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/abc338c9-85df-49a2-9224-ebc02d3ab935)

- 반응형
![반응형4](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/ff53b7cc-dbac-42d6-b26f-7d28726f13d5)

- 태그
![태그](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/136ffcb4-f5c1-4b29-a620-5e732872b858)

   - 인풋창에 태그 입력 후 엔터키를 누르면 태그 목록창으로 변하며, 태그가 생성됩니다.
   - 생성된 태그를 클릭하면 태그가 삭제됩니다.
   - 인풋창 상태에서 수정/추가 버튼을 클릭하면 입력된 태그 목록이 표시되고, 태그를 삭제하거나 추가 할 수있습니다.
   - 태그 목록창에서 수정/추가 버튼을 클릭하면 인풋창으로 돌아갑니다.

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [x] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

2024-02-06 08:19 UTC, muyahho approved these changes
고생하셨습니다!

2024-02-07 04:55 UTC, SeanKim-416 approved these changes
고생하셨습니다. 마지막까지 계속 달려봅시다!

2024-02-07 04:55 UTC, SeanKim-416 commented on taskify-web/src/components/commons/feat-create-card-modal/type.ts
> +}
이부분은 나중에 합치면서 types/ 폴더에 합쳐도 되겠군요!

2024-02-07 06:37 UTC, dahee0401 approved these changes
굿입니다!

2024-02-07 10:04 UTC, nakyoung98 requested changes
화이팅~

2024-02-07 10:04 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-tag-input/TagInput.tsx
> +              key={index}
eslint 오류가 발생했을 것입니다..
data를 넘기면 아마 오류가 나지 않을 것 같네요~

2024-02-07 10:04 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.tsx
> +            <ProgressChip text={ColumnDataState?.title || ''} />
size 잘 빼주셨네요

2024-02-07 10:04 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-user-state-dropdown/UserStateDropdown.tsx
> +      id: 0,
요기에 0이 들어간 이유가 궁금하군요

2024-02-08 04:27 UTC, nakyoung98 approved these changes
새벽에 고생 많으셨어요

2024-02-08 04:27 UTC, merged