feat: Subject Chip 구현
Team-Taskify/Taskify-Web pull request #41
Opened 2024-01-27 06:44 UTC by muyahho

2024-01-27 06:58 UTC, nakyoung98 commented
풀리퀘에 내용이 없어요~ !!!

2024-01-27 07:17 UTC, SeanKim-416 requested changes

2024-01-27 07:17 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  padding: 0.2857rem 0.4286rem;
figma 상에서 기준이 16px 으로 되어있나보네요 10px 기준으로 설정하는게 있으니 그거 적용하셔야 될 듯 합니다.

2024-01-27 07:17 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  font-family: Pretendard;
기본 글꼴로 적용되어 있으니 font-family는 지우셔도 될 것 같습니다.

2024-01-27 07:17 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +const localCx = cx.bind(styles);
```
import classNames from 'classnames/bind';
import styles from './ChipSubject.module.scss';

const cx = classNames.bind(styles);

```

이렇게 수정 부탁드립니다. 컨벤션이에요~

2024-01-27 07:17 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +}
범용적이 아닌 props와 같은 부분은 type을 쓰기로 했죠.
ChipSubject니까 ChipSubjectProps로 사용하는게 가독성 측면에서 좋을 것 같습니다.

2024-01-27 07:17 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +    <div className={localCx('chip')} data-label={label}>
data-label을 사용하신 이유가 있을까요?

2024-01-27 10:03 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  padding: 0.2857rem 0.4286rem;
네 수정하겠습니다.

2024-01-27 10:03 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  font-family: Pretendard;
네 수정하겠습니다

2024-01-27 10:05 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +const localCx = cx.bind(styles);
넵 감사합니다. 수정하겠습니다.

2024-01-27 10:06 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +}
넵 수정하겠습니다.

2024-01-27 10:16 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +    <div className={localCx('chip')} data-label={label}>
사용자 정의 데이터를 HTML 요소에 추가하는 방법에 적용하기위해 여기서 data-label 속성은 스타일링을 위한 특정 선택자를 나타내며, 해당 속성 값을 사용하여 특정 레이블에 대한 스타일을 지정해주고 4가지 레벨에 적용해주었습니다.

2024-01-28 01:01 UTC, SeanKim-416 approved these changes
요청한 사항 전반적으로 잘 수정해주셨습니다. 고생하셨어요!

2024-01-28 01:01 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
요것만 지우면 깔끔하겠네요!

2024-01-28 01:01 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +};
잘 고쳐주셨네요! 다른 컴포넌트 만들때도 요 형식 참고하시면서 진행하면 될 것 같습니다!

2024-01-28 04:26 UTC, nakyoung98 requested changes

2024-01-28 04:26 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  &[data-label='프로젝트'] {
지금은 이거 임시로 잘 해놓으셨지만!
사용자가 직접 기입하는 태그 형식이라서 아마 들어가는 label을 우리가 특정할 수 없을거에요 ~.~
그런의미로 할일에 하나 남겨놔주셔요

2024-01-28 04:26 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +    <div className={cx('chip')} data-label={label}>
span 쓰는 것이, 앞으로 내용 구현에 있어서 더 편할 것 같아요!

![image](https://github.com/Team-Taskify/Taskify-Web/assets/66313756/8f3dbff0-a375-4856-9b2d-8451424d14e2)
저희희가 앞으로 이 태그를 쓰는 방식이,
태그를 사용자가 입력할 때 콤마구분으로 input event가 감지해서 자동으로 글자를 Subjet Chip으로 바꿀 것 같아요.

# [예시]
![1](https://github.com/Team-Taskify/Taskify-Web/assets/66313756/3995f831-7e51-4fd5-a8a4-134c53e86ad9)

2024-01-28 04:59 UTC, jeongseongwon94 approved these changes
더 수정하실부분은 없는거같아요 수고많으셨습니다.

2024-01-28 05:39 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.module.scss
> +  &[data-label='프로젝트'] {
그럼 수정해야겠군요 알겠습니다!

2024-01-28 05:39 UTC, muyahho commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +    <div className={cx('chip')} data-label={label}>
네 그럴게요 수정시에 같이 span으로 수정하면 될것 같아요

2024-01-28 07:07 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-chip-subject/chipSubject.tsx
> +    <div className={cx('chip')} data-label={label}>
그러면 노션에서 컴포넌트단위 할일에 추가해주셔요
작성하실때 꼭 분류추가하셔야해요 안그러면 안보여용 (컴포넌트,칩)

2024-01-28 09:20 UTC, nakyoung98 approved these changes

2024-01-28 09:20 UTC, merged