42 대형 버튼 구현(추가버튼)
Team-Taskify/Taskify-Web pull request #43
Opened 2024-01-27 10:47 UTC by SeanKim-416

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
+ 칩이 있는 대형 추가버튼 컴포넌트 입니다.
props로는 addCase, onClick이 있습니다.
- addCase : 피그마 상 경우가 컬럼추가(addColumn), 할일 추가(addToDo), 대시보드 추가(addDashBoard) 세종류라 세종류입니다.
- 텍스트의 경우 커스터마이징 할 필요가 없어 constant.ts 에 상수로 넣어놨습니다. (상수로 뺄게 많으면 constant 로 사용하는데, 한가지 변수더라도 일관된 코드 가독성 고려해 이대로 가는게 좋을 것 같아 건의 해봅니다)
- onClick : 그냥 버튼동작 관련

## 관련 티켓 및 문서

- Related Issue #42 
- Closes #42 

## 스크린샷, 녹화
- 데탑
<img width="603" alt="스크린샷 2024-01-27 오후 5 17 31" src="https://github.com/Team-Taskify/Taskify-Web/assets/56223156/4f157881-8ed6-4d0c-933c-25033cc12b94">

- 태블릿
<img width="758" alt="스크린샷 2024-01-27 오후 5 17 37" src="https://github.com/Team-Taskify/Taskify-Web/assets/56223156/c9f7928f-ca35-4792-b88f-7e5e1f6b6359">

- 모바일
<img width="571" alt="스크린샷 2024-01-27 오후 5 17 43" src="https://github.com/Team-Taskify/Taskify-Web/assets/56223156/5dfdad46-313d-4036-b462-206f05a8aefb">

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

## [선택사항] 이 PR을 가장 잘 설명하는 GIF는 무엇인가요?

2024-01-27 11:08 UTC, muyahho approved these changes

2024-01-28 04:58 UTC, nakyoung98 requested changes
만약 필요 없는 주석이라면 지우고,
필요한 주석이라면 조금 더 명확한 주석 부탁드려요!

2024-01-28 04:58 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-add-button/AddButton.tsx
> +// addColumn, addDashBoard, addToDo
이 주석은 혹시 어떤 의미일까용?

2024-01-28 04:58 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-add-button/constant.ts
> +  addToDo: '',
안그래도 이런 const text들을 한데 모아서 관리 (추후 외국어 지원시 편리, react-i18? 이런 라이브러리를 쓴다던데 잘은 모르겠고..) 하는 방안을 고민중이에요.
의견 있으신지요~~

2024-01-28 05:07 UTC, jeongseongwon94 approved these changes
수고하셨습니다.

2024-01-28 05:19 UTC, nakyoung98 approved these changes

2024-01-28 05:19 UTC, merged