44 대형 삭제버튼 구현
Team-Taskify/Taskify-Web pull request #46
Opened 2024-01-27 11:06 UTC by SeanKim-416

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
대형 삭제버튼

## 관련 티켓 및 문서

- Related Issue #44 
- Closes #44 

## 스크린샷, 녹화

![스크린샷 2024-01-27 오후 7 59 28](https://github.com/Team-Taskify/Taskify-Web/assets/56223156/b71cf14e-f051-4ec9-9f41-1a54814e3211)

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

## [선택사항] 이 PR을 가장 잘 설명하는 GIF는 무엇인가요?

2024-01-27 11:08 UTC, muyahho approved these changes
감사합니다! 고생많으셨어요 ㅎㅎ

2024-01-28 05:13 UTC, jeongseongwon94 approved these changes
수고하셨습니다.

2024-01-28 05:31 UTC, nakyoung98 requested changes

2024-01-28 05:31 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-delete-button/DeleteButton.tsx
> +      대시보드 삭제하기
delete button보다는 dash delete button같은 것으로 해도 될 것같아요
대시보드 삭제에만 쓰이는 버튼이라 혼동을 피해보죠!

2024-01-28 05:33 UTC, nakyoung98 approved these changes

2024-01-28 05:33 UTC, merged