Feat26 서브 헤더 구현
Team-Taskify/Taskify-Web pull request #48
Opened 2024-01-27 20:27 UTC by jeongseongwon94

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명

- DashboardName 컴포넌트 : 대시보드를 생성한 유저의 id와 현재 접속한 유저의 id가 동일하다면 표시,
대시보드의 이름을 api로 가져와서 title props에 전달해줘야 할꺼같습니다.
- SubHeaderButton 컴포넌트 - 대시보드를 생성한 유저의 id와 현재 접속한 유저의 id가 동일하다면 표시
- MyProfile 컴포넌트 - 접속한 유저의 닉네임과 프로필이미지를 props로 전달

## 관련 티켓 및 문서

- Related Issue #26 
- Closes #26 

## 스크린샷, 녹화

![11](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/15fb2c7f-ac2e-4318-8aa9-de29f931ec93)

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

## 질문
- 아래 스크린샷과 같이 TODO 멤버리스트 오른쪽에 위치한 구분선의 위치랑 내 프로필, 이미지의 위치를 잘못 지정한거같아요..
어떻게 수정해야할지 모르겠습니다..
- 반응형 디자인에 따라서 태블릿과 모바일에서는 일부 컴포넌트가 안보이도록해야하는데 커스텀훅이 필요한걸까요..?

2024-01-27 22:45 UTC, muyahho approved these changes
감사합니다 고생하셨어요 ㅎㅎ

2024-01-28 01:10 UTC, SeanKim-416 approved these changes
컴포넌트 내에서 잘 나눠주셨네요. 추가적으로 개발하면서 재사용이 될 것 같은 컴포넌트는 나중에 다른 디렉토리로 옮기는 방향도 좋을 것 같습니다. 안되는 부분은 코어타임때 같이 확인해보죠

2024-01-28 01:10 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-sub-header/DashboardName.module.scss
> +}
작은 컴포넌트 단위로 잘 쪼개주셨네요!

2024-01-28 01:13 UTC, SeanKim-416 commented
1. 스크린샷과 같이 TODO 멤버리스트 오른쪽에 위치한 구분선의 위치랑 내 프로필, 이미지의 위치를 잘못 지정한거같아요..
어떻게 수정해야할지 모르겠습니다..
- 이부분은 제가 이슈파서 한번 확인해보겠습니다.

2. 반응형 디자인에 따라서 태블릿과 모바일에서는 일부 컴포넌트가 안보이도록해야하는데 커스텀훅이 필요한걸까요..?
- 스타일 자체로도 지정은 가능할 것 같습니다.

3. provider관련해서 다시 공부해올게요 ..
- provider는 페이지 자체에서 또는 _app.tsx에서 유저관련 정보를 제공하는 게 맞을 것 같기 때문에 지금은 고려하지 않아도 될 것 같습니다.

2024-01-28 05:13 UTC, dahee0401 approved these changes

2024-01-28 05:13 UTC, dahee0401 commented on taskify-web/src/components/commons/ui-sub-header/DashboardName.module.scss
> +}
좋아요

2024-01-28 09:01 UTC, muyahho approved these changes
성원님 고생많으셨습니다 !
질문주신거 읽어봤는데요 
모바일 및 태블릿에서 일부 컴포넌트를 숨겨야 하는 경우 커스텀 훅에대해서 여쭤보셨는데, CSS 미디어 쿼리를 사용하여 반응형 디자인을 추가하는 방법도 있는것 같고요
말씀하신 훅 사용도 좋죠! 훅을 사용하실 경우에는
useMediaQuery와 같은 훅을 사용해.
 isTabletOrMobile이 true일 때만 DashboardUserList와 MyProfile이 렌더링하도록 하면 될것 같네
 
 말씀하신 구분선 위치조정같은 경우 
 SubHeaderItemsRight 컴포넌트 내에서 구분선 렌더링법확인후
 해당 컴포넌트에서 구분선을 렌더링하고 있다면,  스타일시트에서 position, top, right, bottom, left 등을 이용하여 위치를 조정은 가능할까요? 우선 밖이라 이정도로 답변이 가능할것 같네용
 고생많으셨어요 미소천사님 ㅎㅎ 화이팅

2024-01-28 10:51 UTC, nakyoung98 requested changes

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/DashboardSubHeader.tsx
> +        <MyProfile nickname="배유철" profileImageUrl="" />
테스트 코드는 PR 할때, Commit할때 제외해주세요!

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/SubHeader.module.scss
> +  box-shadow: 0 1px 0 0 $gray_d9d9d9;
rem! 한번만 부탁드려요

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/SubHeader.module.scss
> +  box-shadow: 0 1px 0 0 $gray_d9d9d9;
그리고 shadow도 $outline 이용하시면 됨다

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.module.scss
> +  border: 0.1rem solid $gray_d9d9d9;
요것도 $outline 부탁드려용

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderItemsLeft.module.scss
> +.container {
이친구는 별도로 align을 center로 하지 않아도 어떤 상황에서도 y축기준 중앙에 표시되나요?

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/MyProfile.tsx
> +import classNames from 'classnames/bind';
이거 보니까 드롭다운에서도 쓰는 곳이 있더라구요
그때 사람들이 실수로 또 만들지 않게, 다른 commons 폴더에 따로  ProfileLabel 같은 컴포넌트 이름 하나 지으셔서 올려주시고,
PR명도 서브헤더만 두지마시고 서브헤더 및 .. 구현으로 하시죠

2024-01-28 10:51 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.tsx
> +    <>
이거 id는 항상 prop으로 전달될 것 같은데.. 혹시 아닌가요?

2024-01-28 10:52 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/DashboardSubHeader.tsx
> +        <MyProfile nickname="배유철" profileImageUrl="" />
넵 수정했습니다

2024-01-28 11:07 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/SubHeader.module.scss
> +  box-shadow: 0 1px 0 0 $gray_d9d9d9;
넵 수정했습니다

2024-01-28 11:08 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.module.scss
> +  border: 0.1rem solid $gray_d9d9d9;
넵 수정했습니다.

2024-01-28 11:17 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderItemsLeft.module.scss
> +.container {
엇 이쪽은 정렬안되고있었네요 상위 컴포넌트 SubHeaderItems에 align center하였습니다. 감사합니다.

2024-01-28 11:31 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/MyProfile.tsx
> +import classNames from 'classnames/bind';
넵 ProfileLabel 컴포넌트로 수정해서 폴더 위치변경하였습니다.

2024-01-28 11:40 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-sub-header/SubHeaderButton.tsx
> +    <>
그렇네요 기본값을 null로해서 옵셔널로 수정했습니다 감사합니다.

2024-01-28 12:47 UTC, SeanKim-416 approved these changes
고생하셨습니다! map 사용하는 부분등 추후에 제작할 거는 차근차근 진행해가도 될 것 같습니다!

2024-01-29 03:21 UTC, nakyoung98 approved these changes

2024-01-29 03:21 UTC, merged