Feat47 페이지네이션 컴포넌트 구현
Team-Taskify/Taskify-Web pull request #53
Opened 2024-01-28 08:05 UTC by dahee0401

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
PaginationButton컴포넌트 : disabled될 시,  PaginationButton 컴포넌트에 프롭스로 전달

## 관련 티켓 및 문서

- Related Issue #47 
- Closes #47 

## 스크린샷, 녹화

<img width="245" alt="스크린샷 2024-01-28 오후 4 46 30" src="https://github.com/Team-Taskify/Taskify-Web/assets/88355842/d3cc84aa-8f8d-4dc8-aa83-0a185084bb02">

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

2024-01-28 08:06 UTC, muyahho approved these changes

2024-01-28 08:19 UTC, SeanKim-416 requested changes

2024-01-28 08:19 UTC, SeanKim-416 commented on taskify-web/src/components/ui-pagination/PaginationButton.tsx
> +
svgr 사용해서 컴포넌트화 하시면 사용하시기 편할 것 같습니다!
```tsx
import ArrowIcon from './arrow.svg'
```

2024-01-28 08:19 UTC, SeanKim-416 commented on taskify-web/src/components/ui-pagination/PaginationButton.tsx
> +        {children}
svgr을 사용하면 이렇게 쓰면 되겠죠
```tsx
return (
    <div className={paginationContainerClass}>
      <button
        type="button"
        className={paginationbuttonClass}
        onClick={onClick}
        disabled={disabled}
      >
         <ArrowIcon />
```

2024-01-28 08:26 UTC, nakyoung98 requested changes

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.module.scss
> +  &.disabled {
opacity를 Button 자체에 주시면 버튼 전체가 opacity가 낮아져서요! 만약 배경색이 하얀색이 아니면 못생긴 디자인이 될 수도 있어용 (버튼이 잘 안보일 수도 있고요)

그래서 SVG Component에 className={cx('arrow')} 같은 Prop을 전달하신 후에 scss내에서 &:disabled { .arrow{opacity:0.3;}} 같이 사용하시는 것은 어때요?

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.module.scss
> +    border-radius: 4px 0px 0px 4px;
rem으로 바꿔주세요!

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.module.scss
> +    border: 1px solid var(--gray-gray_D9D9D9, #d9d9d9);
이건 variables라는 scss 파일에 outline이라는 변수로 색상이 정의 되어있어요

Notion 컨벤션에 색상 시스템 문서 한번 봐주세요

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.module.scss
> +    background: var(--white-white_FFFFFF, #fff) url('./arrow.svg') center
이 부분도 아마 정의되어있을거에용

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.module.scss
> +    background: var(--white-white_FFFFFF, #fff) url('./arrow.svg') center
그리고 이거 svgr 사용하셔서 이미지 한번 불러와보시겠어요?

그 노션에 svgr 사용법 컨벤션 보심 됨다

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.tsx
> +        {children}
여기 안에 들어가는 이미지는 어짜피 고정이고 더 들어갈내용이 없을것같아요!
 children 받을 필요 없을 것 같아요

2024-01-28 08:26 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.tsx
> +      >
그리고 이거!
button 두개를 하나의 Pagination Button에 넣으셔도 되지만,
버튼 하나만있는 PaginationButton을 구현하신 후에,
PaginationButton 두개를 붙인 컴포넌트를 추가로 만들어 보는건 어떠신가요?

![image](https://github.com/Team-Taskify/Taskify-Web/assets/66313756/547f26b4-ed49-4e5f-b0b4-c7939e9b9f8b)

2024-01-28 11:25 UTC, nakyoung98 requested changes

2024-01-28 11:25 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButton.tsx
> +// import ArrowIcon from './ArrowIcon';
요거 안쓰니까 지워주세용!

2024-01-28 11:25 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/PaginationButtonContainer.tsx
> +          console.log('왼쪽');
콘솔은 eslint에서 주의사항이라 테스트 후 지워주세요!

2024-01-28 11:25 UTC, nakyoung98 commented on taskify-web/src/pages/index.tsx
> +// import PaginationButton from '../components/ui-pagination/PaginationButton';
헉 
이거 index는 테스트 하신거라서 변경사항 커밋하시면 안돼요!

2024-01-28 12:44 UTC, SeanKim-416 approved these changes
고생하셨습니다! 리뷰 드린 부분 전부 반영해주셨네요!

2024-01-29 03:18 UTC, nakyoung98 requested changes

2024-01-29 03:18 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/ArrowSvg.tsx
> +import React from 'react';
요고 안쓰는 파일이니까 삭제해서 커밋 부탁드려요!

2024-01-29 03:19 UTC, jeongseongwon94 approved these changes
수고하셨습니다.

2024-01-29 03:21 UTC, nakyoung98 commented on taskify-web/src/components/ui-pagination/ArrowSvg.tsx
> +import React from 'react';
ArrowSvg.tsx자체를 삭제해주시면 됩니다

2024-01-29 08:45 UTC, nakyoung98 approved these changes

2024-01-29 08:46 UTC, merged