Feat70 인풋 공통 모달 구현
Team-Taskify/Taskify-Web pull request #77
Opened 2024-01-30 08:29 UTC by dahee0401

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
인풋 공통으로 되어있는 모달 구현 (컬럼관리, 새컬럼 생성, 초대하기 모달)

## 관련 티켓 및 문서

- Related Issue #70 
- Closes #70 

## 스크린샷, 녹화
<img width="1437" alt="스크린샷 2024-01-30 오후 5 21 45" src="https://github.com/Team-Taskify/Taskify-Web/assets/88355842/aaf0b4d9-78fd-4f3f-86d4-6a7e94cee326">

<img width="376" alt="스크린샷 2024-01-30 오후 5 22 04" src="https://github.com/Team-Taskify/Taskify-Web/assets/88355842/de1ad6a7-8e70-4f44-904e-19abb4bbe604">

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

## [선택사항] 이 PR을 가장 잘 설명하는 GIF는 무엇인가요?

2024-01-30 08:37 UTC, nakyoung98 requested changes

2024-01-30 08:37 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-input-modal/InputModal.tsx
> +          <ModalHeader className={cx('modal-header')}>모달제목</ModalHeader>
이 부분 다른 곳에서 데이터를 받으려면 Prop에서 문자열을 받아야할 것 같아요!!

2024-01-31 04:25 UTC, SeanKim-416 approved these changes

2024-01-31 04:25 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-input-modal/InputModal.tsx
> +          <ModalHeader className={cx('modal-header')}>모달제목</ModalHeader>
InputModalProps 타입을 하나 파서 텍스트를 넣어주게 하는 방식으로 하면 될 것 같습니다.

2024-01-31 04:25 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-input-modal/InputModal.tsx
> +              onChange={handleChange}
기능적으로 동작할 땐 나중에 폼에서 컨트롤 하는 방식으로 해도 괜찮겠네요. 지금 당장은 아니고 이해하고 계시면 될 것 같습니다!

2024-01-31 04:46 UTC, muyahho approved these changes
고생하셨습니다!

2024-01-31 04:47 UTC, jeongseongwon94 approved these changes
수고하셨습니다.

2024-01-31 16:57 UTC, nakyoung98 approved these changes

2024-01-31 16:58 UTC, merged