Feat73 드롭다운 구현
Team-Taskify/Taskify-Web pull request #79
Opened 2024-01-30 15:39 UTC by jeongseongwon94

## 이 PR은 어떤 유형인가요?

- [ ] 리팩터링
- [x] 기능
- [ ] 버그 수정
- [ ] 최적화
- [ ] 문서 업데이트

## 설명
props
- buttonList : 드롭다운 목록에서 사용할 버튼의 이름을 가져옵니다.  가져온 버튼 이름의 개수 만큼 버튼이 생성됩니다.
- onClick : 버튼에서 실행될 함수를 가져옵니다. input.innerText를 사용하여 특정 버튼의 이름을 조건문으로 작성하시면 됩니다.
- isKebab :  케밥 이미지의 표시 여부를 선택합니다. 기본값은 false입니다.
- children : 케밥 이미지가 아닌 특정 태그/컴포넌트의 위치에서 드롭다운을 동작시킬 수 있습니다. 해당 태그/컴포넌트의 부모 요소로 Dropdown 컴포넌트를 가져오면 됩니다.

## 관련 티켓 및 문서

- Related Issue #73 
- Closes #73 

## 스크린샷, 녹화

![드롭다운](https://github.com/Team-Taskify/Taskify-Web/assets/148832721/797fe78a-d247-4cbd-aec7-cdb9feb8ba4d)

- 테스트 코드

```
import Dropdown from '@/components/commons/ui-dropdown/Dropdown';

export default function Home() {
  const testButtonList = {
    modal: ['수정하기', '삭제하기'],
    nav: ['로그아웃', '내 정보', '내 대시보드'],  // 드롭다운 박스 내 표시 할 버튼 목록
  };

  const handleButtonClick = async (e: React.MouseEvent) => {  
   // 특정 버튼에서 실행 될 함수는 innerText를 사용하여 작성하시면됩니다. 
    const input = e.target as HTMLElement;

    if (input.innerText === '수정하기') {
      console.log('콘솔콘솔');
    }

    if (input.innerText === '삭제하기') {
      console.log('콘솔콘솔');
    }
  };

  return (
    <div>
      <div>
        <Dropdown
          buttonList={testButtonList.modal}
          onClick={handleButtonClick}
          isKebab
        />
      </div>
      <div>
        <Dropdown buttonList={testButtonList.nav} onClick={handleButtonClick}>
          <span>닉네임</span>  // 닉네임 태그 클릭 시 드롭다운 목록 표시
        </Dropdown>
      </div>
    </div>
  );
}
```

### UI 접근성 체크리스트

_UI 변경 사항이 있는 경우, 이 체크리스트를 활용하세요:_
- [ ] Semantic HTML 구현?
- [ ] 키보드 조작이 지원?
- [ ] [axe DevTools](https://www.deque.com/axe/)를 사용하여 Critical 및 Serious 문제를 확인하고 해결했나요?

2024-01-30 17:56 UTC, nakyoung98 requested changes

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    color: $primary;
hover 잘 적용해주셨지만 테스트 영상에서는 없네요 ㅠ,ㅠ

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    font-size: $font_size_small;
font-size: $font_size_small;
    
이거 button의 모든 상태에서 동일한 size인 것 같은데요,
중복되는 부분을 지우시고, .button 안에 하나만 넣는 것은 어떠신지요?

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    font-size: $font_size_xsmall;
:)

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    font-size: $font_size_small;
:)

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  buttonList: string[];
routeList도 좋을 것 같아요 (그냥 의견)

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  isKebab?: boolean;
케밥 먹고싶네요 제가 케밥 진짜 좋아하는데 여기 을지로 인근에 케밥으로 웨이팅하는 집 하나 있거든요
사람이 너무 많고 웨이팅 심해서 못가봤어요

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  const [isDropdownView, setIsDropdownView] = useState<boolean>(false);
isDropped, setisDropped 는 어떠세요?

2024-01-30 17:56 UTC, nakyoung98 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +        {isKebab && <Kebab />}
kebab씨의 width나 height는 잘 정의되어있나요?

2024-01-31 03:43 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    color: $primary;
넵 이미지 수정했습니다.

2024-01-31 03:47 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  buttonList: string[];
수정 삭제하기 버튼도 사용해야해서 button이들어가는게 좋을꺼같아요 아마도..

2024-01-31 03:48 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  isKebab?: boolean;
굳 케밥 맛잇겠네요

2024-01-31 03:49 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  const [isDropdownView, setIsDropdownView] = useState<boolean>(false);
넵 반영했습니다

2024-01-31 03:56 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.module.scss
> +    font-size: $font_size_small;
```
@include mobile {
    width: 7.4rem;
    height: 3rem;
    font-size: $font_size_xsmall;
  }
  @include tablet {
    width: 8.1rem;
    height: 3.2rem;
    font-size: $font_size_small;
  }
```
모바일에서는 14px로 줄어드는거 같아서 
이렇게 수정했습니다. 태블릿에만 사이즈를 지정해도 데스크탑에 적용되는거였네요

2024-01-31 04:05 UTC, jeongseongwon94 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +        {isKebab && <Kebab />}
깜빡했네요 svg파일에 지정된 크기 지우고 반응형 css 추가하였습니다.

2024-01-31 04:18 UTC, SeanKim-416 approved these changes

2024-01-31 04:18 UTC, SeanKim-416 commented on taskify-web/src/components/commons/ui-dropdown/Dropdown.tsx
> +  buttonList: string[];
menuList도 괜찮을 것 같네요

2024-01-31 04:37 UTC, dahee0401 commented
좋습니다

2024-01-31 04:38 UTC, dahee0401 approved these changes

2024-01-31 04:42 UTC, muyahho approved these changes
고생하셨습니다!

2024-01-31 04:47 UTC, nakyoung98 approved these changes

2024-01-31 04:48 UTC, merged